---
- name: Secure SSH configuration
  hosts: all
  become: yes
  vars:
    devops_user: "{{ devops_user }}"
  tasks:
    - name: Disable root SSH login
      lineinfile:
        path: /etc/ssh/sshd_config
        state: present
        regexp: '^PermitRootLogin'
        line: 'PermitRootLogin no'
      notify:
        - Restart SSH

    - name: Allow only key-based SSH authentication
      lineinfile:
        path: /etc/ssh/sshd_config
        state: present
        regexp: '^PasswordAuthentication'
        line: 'PasswordAuthentication no'
      notify:
        - Restart SSH

    - name: Allow devops_user to switch to root without a password
      lineinfile:
        path: /etc/sudoers
        state: present
        line: '{{ devops_user }} ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'

  handlers:
    - name: Restart SSH
      service:
        name: sshd
        state: restarted
